# Fixed part
[[main]]
none = "none"

[[main]]
pre = "github"
url = "https://github.com/emrecengdev"
identifier = "github"
weight = 200

[[main]]
pre = "linkedin"
url = "https://www.linkedin.com/in/emre-canik/"
identifier = "linkedin"
weight = 210

[[main]]
pre = "youtube"
url = "https://www.youtube.com/channel/UCK8Gbs97ut8CS_PdPMFW4bg"
identifier = "youtube"
weight = 220

[[main]]
name = "resume"
pageRef = "resume/resume.md"
identifier = "resume"
weight = 40

[[main]]
name = "projects"
pageRef = "projects/index.md"
identifier = "projects"
weight = 50

# Programming category
[[main]]
name = "programlama"
pageRef = "/categories/programlama/"
identifier = "programlama"
weight = 60

# Programming -> Python category
[[main]]
name = "python eğitimi"
parent = "programlama"
pageRef = "python"
identifier = "python"
weight = 70

# Programming -> Software Tools and Applications
[[main]]
name = "araçlar"
parent = "programlama"
pageRef = "/categories/programlama/araclar/"
identifier = "araclar"
weight = 130

# Programming -> Guides and Tutorials
[[main]]
name = "rehberler"
parent = "programlama"
pageRef = "/categories/programlama/rehberler/"
identifier = "rehberler"
weight = 140

# Technology and News
[[main]]
name = "blog"
pageRef = "/categories/blog/"
identifier = "blog"
weight = 160
